import { OnDestroy } from '@angular/core';
import * as i0 from "@angular/core";
export declare class ZoomService implements OnDestroy {
    private zoomMutex;
    private _zoom;
    maxZoom: number;
    minZoom: number;
    private lastDistance;
    private isPinching;
    private ratioX;
    private ratioY;
    private triggerUpdateSizeInternal$;
    triggerUpdateSize$: import("rxjs").Observable<void>;
    set zoom(value: number);
    get zoom(): number;
    private wheelHandler;
    private transformWrapper;
    private transientScale;
    initSettings(container: HTMLElement, transformWrapper: HTMLElement, isWheelZoom: boolean, isWheelCtrlZoom: boolean): void;
    limitZoom(): void;
    private zoomAtCursor;
    private onTouchStart;
    private onTouchMove;
    private onTouchEnd;
    private getDistance;
    saveScrollPosition(container: HTMLElement): void;
    restoreScrollPosition(container: HTMLElement): void;
    removeListeners(container: HTMLElement): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ZoomService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<ZoomService>;
}
